-- DISABLED reference from your previous config/autocmds.lua (not loaded).
--
-- vim.api.nvim_create_autocmd('TextYankPost', {
--   desc = 'Highlight when yanking text',
--   group = vim.api.nvim_create_augroup('highlight-yank', { clear = true }),
--   callback = function()
--     vim.highlight.on_yank()
--   end
-- })
