# shellcheck shell=bash
# Phase 10 — assemble the runtime env from shared + device layers.
# Layering (later wins): shared.env -> devices/<profile>.env -> <profile>.local.env
# The result is written to ~/.config/dotfiles/env.sh and sourced from the shell.

step "Environment ($PROFILE)"

env_out="$DOTFILES_STATE_DIR/env.sh"
mkdir -p "$DOTFILES_STATE_DIR"

layers=(
  "$DOTFILES/env/shared.env"
  "$DOTFILES/env/devices/$PROFILE.env"
  "$DOTFILES/env/devices/$PROFILE.local.env"
)

{
  printf '# Generated by dotfiles install.sh — do not edit; edit env/ sources.\n'
  for layer in "${layers[@]}"; do
    if [ -f "$layer" ]; then
      printf '\n# --- %s ---\n' "${layer#$DOTFILES/}"
      cat "$layer"
    fi
  done
} > "$env_out"
ok "assembled $env_out"

# Wire it into the shell via an idempotent managed block in ~/.zshrc.
zshrc="$HOME/.zshrc"; marker_a='# >>> dotfiles env >>>'; marker_b='# <<< dotfiles env <<<'
if [ -f "$zshrc" ] && grep -qF "$marker_a" "$zshrc"; then
  skip "~/.zshrc already sources dotfiles env"
else
  {
    printf '\n%s\n' "$marker_a"
    printf '[ -f "%s" ] && source "%s"\n' "$env_out" "$env_out"
    printf '%s\n' "$marker_b"
  } >> "$zshrc"
  ok "added env block to ~/.zshrc"
fi
