-- DISABLED reference from your previous config.
-- To re-enable: uncomment the spec below and delete the trailing 'return {}'.
-- (Note: old keymaps used custom group()/m.* helpers that no longer exist —
--  adapt them to vim.keymap.set when reviving.)
--
-- return {
--   'NeogitOrg/neogit',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     'sindrets/diffview.nvim',
--   },
--   opts = {
--     enchaned_diff_hl = true,
--   },
--   config = function()
--     vim.opt.fillchars:append({ diff = '/' })
-- 
--     group('Neogit', function(m)
--       m.normal('<leader>gg', '<cmd>Neogit<cr>')
--     end)
--   end
-- }

return {}
