-- DISABLED reference from your previous config.
-- To re-enable: uncomment the spec below and delete the trailing 'return {}'.
-- (Note: old keymaps used custom group()/m.* helpers that no longer exist —
--  adapt them to vim.keymap.set when reviving.)
--
-- return {
--   {
--     'MeanderingProgrammer/render-markdown.nvim',
--     dependencies = {
--       'nvim-treesitter/nvim-treesitter',
--       'nvim-mini/mini.nvim',
--     },
--     opts = {}
--   },
--   {
--     "iamcco/markdown-preview.nvim",
--     cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
--     build = "cd app && bun install",
--     init = function()
--       vim.g.mkdp_filetypes = { "markdown" }
--     end,
--     ft = { "markdown" },
--   },
-- }

return {}
