-- DISABLED reference from your previous config.
-- To re-enable: uncomment the spec below and delete the trailing 'return {}'.
-- (Note: old keymaps used custom group()/m.* helpers that no longer exist —
--  adapt them to vim.keymap.set when reviving.)
--
-- ---@type LazySpec
-- return {
--   "mikavilpas/yazi.nvim",
--   version = "*", -- use the latest stable version
--   event = "VeryLazy",
--   dependencies = {
--     { "nvim-lua/plenary.nvim", lazy = true },
--   },
--   keys = {
--     -- 👇 in this section, choose your own keymappings!
--     {
--       "<leader>-",
--       mode = { "n", "v" },
--       "<cmd>Yazi<cr>",
--       desc = "Open yazi at the current file",
--     },
--     {
--       -- Open in the current working directory
--       "<leader>cw",
--       "<cmd>Yazi cwd<cr>",
--       desc = "Open the file manager in nvim's working directory",
--     },
--     {
--       "<c-up>",
--       "<cmd>Yazi toggle<cr>",
--       desc = "Resume the last yazi session",
--     },
--   },
--   ---@type YaziConfig | {}
--   opts = {
--     -- if you want to open yazi instead of netrw, see below for more info
--     open_for_directories = true,
--     keymaps = {
--       show_help = "<f1>",
--     },
--   },
--   -- 👇 if you use `open_for_directories=true`, this is recommended
--   init = function()
--     -- mark netrw as loaded so it's not loaded at all.
--     --
--     -- More details: https://github.com/mikavilpas/yazi.nvim/issues/802
--     -- vim.g.loaded_netrwPlugin = 1
--   end,
-- }

return {}
